# Generated by Django 6.0.6 on 2026-06-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(help_text='Default recipient email for daily digest', max_length=254)),
                ('smtp_host', models.CharField(max_length=256)),
                ('smtp_port', models.IntegerField()),
                ('smtp_user', models.CharField(max_length=256)),
                ('smtp_password', models.CharField(max_length=512)),
                ('use_tls', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'email config',
                'verbose_name_plural': 'email config',
            },
        ),
    ]
