# Generated by Django 6.0.6 on 2026-06-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_emailconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfig',
            name='smtp_host',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='smtp_password',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='smtp_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='smtp_user',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
