# Generated by Django 6.0.6 on 2026-06-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_emailconfig_smtp_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfig',
            name='to_email',
            field=models.EmailField(blank=True, default='', help_text='Default recipient email for daily digest', max_length=254),
        ),
    ]
