# Generated by Django 6.0.6 on 2026-06-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_emailconfig_to_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=64)),
                ('published_date', models.CharField(max_length=32)),
                ('closing_date', models.CharField(max_length=32)),
                ('opening_date', models.CharField(max_length=32)),
                ('title', models.TextField()),
                ('reference_identifiers', models.JSONField(default=list)),
                ('organization_chain', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'tenders',
                'ordering': ['-created_at'],
            },
        ),
    ]
